version: "3"
services:
       sellingbooks:
           container_name: sellingbooks
           image: sellingbooks
           restart: always
           build: .
           ports:
             - "8080:8080"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'